spring:
  application:
    name: delivery-api

 #Configuracao do Banco de Dados do PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5433/delivery_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update # Cria/atualiza tabelas automaticamente
      show-sql: true   # Mostra o SQL no console
      properties:
        hibernate:
          format_sql: true # Formata o SQL para ficar mais legï¿½vel
